<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>Normalize Geographic Variables</title>

<script src="data:application/javascript;base64,Ly8gUGFuZG9jIDIuOSBhZGRzIGF0dHJpYnV0ZXMgb24gYm90aCBoZWFkZXIgYW5kIGRpdi4gV2UgcmVtb3ZlIHRoZSBmb3JtZXIgKHRvCi8vIGJlIGNvbXBhdGlibGUgd2l0aCB0aGUgYmVoYXZpb3Igb2YgUGFuZG9jIDwgMi44KS4KZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGZ1bmN0aW9uKGUpIHsKICB2YXIgaHMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCJkaXYuc2VjdGlvbltjbGFzcyo9J2xldmVsJ10gPiA6Zmlyc3QtY2hpbGQiKTsKICB2YXIgaSwgaCwgYTsKICBmb3IgKGkgPSAwOyBpIDwgaHMubGVuZ3RoOyBpKyspIHsKICAgIGggPSBoc1tpXTsKICAgIGlmICghL15oWzEtNl0kL2kudGVzdChoLnRhZ05hbWUpKSBjb250aW51ZTsgIC8vIGl0IHNob3VsZCBiZSBhIGhlYWRlciBoMS1oNgogICAgYSA9IGguYXR0cmlidXRlczsKICAgIHdoaWxlIChhLmxlbmd0aCA+IDApIGgucmVtb3ZlQXR0cmlidXRlKGFbMF0ubmFtZSk7CiAgfQp9KTsK"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="data:text/css,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" type="text/css" />




</head>

<body>




<h1 class="title toc-ignore">Normalize Geographic Variables</h1>



<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(campfin)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">packageVersion</span>(<span class="st">&quot;campfin&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] &#39;1.0.7&#39;</span></span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code></pre></div>
<div id="background" class="section level2">
<h2>Background</h2>
<p>This vignette contains an example of the workflow used by the wranglers on <a href="https://www.publicaccountability.org/">The Accountability Project</a>, a tool created by <a href="https://investigativereportingworkshop.org/">The Investigative Reporting Workshop</a> in Washington, DC. The Accountability Project curates, cleans, and indexes public data to give journalists, researchers, and the public a simple way to search across otherwise siloed records. The data focuses on people, organizations and locations.</p>
<p>Since state-level campaign finance data is typically reported by the campaigns and provided to them by the contributors themselves, there is often great disparity in data quality. The campfin package was created to reduce this disparity in a consistent, confident, and programmatic way.</p>
</div>
<div id="messy-data" class="section level2">
<h2>Messy Data</h2>
<p>In this vignette, we will clean some exaggerated fake messy contribution data from a fictitious campaign in Vermont. This data is found in the <code>vt_contribs.csv</code> file included with our package.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ex_file <span class="ot">&lt;-</span> <span class="fu">system.file</span>(<span class="st">&quot;extdata&quot;</span>, <span class="st">&quot;vt_contribs.csv&quot;</span>, <span class="at">package =</span> <span class="st">&quot;campfin&quot;</span>)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="2%" />
<col width="11%" />
<col width="10%" />
<col width="6%" />
<col width="12%" />
<col width="23%" />
<col width="13%" />
<col width="7%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">cand</th>
<th align="left">date</th>
<th align="left">amount</th>
<th align="left">name</th>
<th align="left">address</th>
<th align="left">city</th>
<th align="left">state</th>
<th align="left">zip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">01</td>
<td align="left">Bob Miller</td>
<td align="left">02/09/2019</td>
<td align="left">10</td>
<td align="left">Lisa Miller</td>
<td align="left">4 Sheffield square Road</td>
<td align="left">Sheffield</td>
<td align="left">VT</td>
<td align="left">05866</td>
</tr>
<tr class="even">
<td align="left">02</td>
<td align="left">Bob Miller</td>
<td align="left">03/09/2009</td>
<td align="left">20</td>
<td align="left">Deb Brown</td>
<td align="left">Requested</td>
<td align="left">Requested</td>
<td align="left">RE</td>
<td align="left">00000</td>
</tr>
<tr class="odd">
<td align="left">03</td>
<td align="left">Chuck White</td>
<td align="left">04/09/2019</td>
<td align="left">25</td>
<td align="left">N/A</td>
<td align="left">p.o. box 567</td>
<td align="left">Midlebury</td>
<td align="left">Vermont</td>
<td align="left">05753-0567</td>
</tr>
<tr class="even">
<td align="left">04</td>
<td align="left">Chuck White</td>
<td align="left">05/09/2019</td>
<td align="left">100</td>
<td align="left">Josh Jones</td>
<td align="left">sugarhouse SQU</td>
<td align="left">e Corinth</td>
<td align="left">VT</td>
<td align="left">5076</td>
</tr>
<tr class="odd">
<td align="left">05</td>
<td align="left">Bob Miller</td>
<td align="left">02/09/2019</td>
<td align="left">10</td>
<td align="left">Lisa Miller</td>
<td align="left">4 Sheffield square Road</td>
<td align="left">Sheffield</td>
<td align="left">VT</td>
<td align="left">05866</td>
</tr>
<tr class="even">
<td align="left">06</td>
<td align="left">Chuck White</td>
<td align="left">06/09/2019</td>
<td align="left">1000</td>
<td align="left">Bob Taylor</td>
<td align="left">55 thisplace av</td>
<td align="left">young america</td>
<td align="left">mn</td>
<td align="left">55555</td>
</tr>
<tr class="odd">
<td align="left">07</td>
<td align="left">Chuck White</td>
<td align="left">07/09/2019</td>
<td align="left">-600</td>
<td align="left">Alex Johnson</td>
<td align="left">11 Liberty AVN</td>
<td align="left">Bristol, VT</td>
<td align="left">VT</td>
<td align="left">99999</td>
</tr>
<tr class="even">
<td align="left">08</td>
<td align="left">Alice Walsh</td>
<td align="left">08/09/2019</td>
<td align="left">0</td>
<td align="left">Ruth Smith</td>
<td align="left">2 Burlington sqre</td>
<td align="left">Brulington</td>
<td align="left">vt</td>
<td align="left">05401</td>
</tr>
<tr class="odd">
<td align="left">09</td>
<td align="left">Alice Walsh</td>
<td align="left">09/09/2019</td>
<td align="left">69</td>
<td align="left">Joe Garcia</td>
<td align="left">770 5th-st-nw</td>
<td align="left">Washington</td>
<td align="left">D.C.</td>
<td align="left">20001-2674</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">Alice Walsh</td>
<td align="left">11/09/2019</td>
<td align="left">222</td>
<td align="left">Dave Wilson</td>
<td align="left">XXXXXXXXXXXXXXXXX</td>
<td align="left">SA</td>
<td align="left">Texas</td>
<td align="left">78202</td>
</tr>
</tbody>
</table>
<p>What are some of the potential problems we can see in this data?</p>
<ul>
<li>The <code>date</code> column is not parsed as an R date, making it impossible to perform mathematical calculations like <code>min()</code>.</li>
<li>There is one negative <code>amount</code> value and another that’s zero. Not necessarily uncommon, but worth noting.</li>
<li>One record is missing both the contributor’s <code>name</code>.</li>
<li>One record is duplicated across every column.</li>
<li>In <code>address</code> we see:
<ul>
<li>Inconsistent capitalization.</li>
<li>A mix of full and abbreviated suffixes.</li>
<li>Alternative versions of <code>NA</code>.</li>
<li>Unnecessary and inconsistent punctuation.</li>
<li>Excess trailing and internal white space.</li>
<li>Incorrect punctuation and replaced spaces.</li>
<li>Repeating character strings used instead of <code>NA</code>.</li>
</ul></li>
<li>In <code>city</code> we see many of the same problems, plus:
<ul>
<li>Geographic abbreviations.</li>
<li>Repeated <code>state</code> information.</li>
<li>Misspellings.</li>
<li>Colloquial city abbreviations.</li>
</ul></li>
<li>In <code>state</code> we see a mix of full and abbreviated state names.</li>
<li>In <code>zip</code>:
<ul>
<li>Repeated digits used for <code>NA</code> values (NB: 55555 is a valid ZIP code, 99999 is not).</li>
<li>Unnecessary and inconsistent <a href="https://en.wikipedia.org/wiki/ZIP_Code#ZIP+4" title="zip4">ZIP+4</a> usage.</li>
<li>Leading zeroes <a href="https://support.microsoft.com/en-us/office/display-numbers-as-postal-codes-61b55c9f-6fe3-4e54-96ca-9e85c38a5a1d?ui=en-us&amp;rs=en-us&amp;ad=us" title="excel">dropped by Excel</a> or some other program.</li>
</ul></li>
</ul>
<p>While this data is obviously much smaller and more full of errors than real campaign finance data, these errors are not uncommon and need to be addressed. The campfin package contains many of the tools we need to first find and then fix these common problems.</p>
</div>
<div id="read" class="section level2">
<h2>Read</h2>
<p>In most cases, the first step is to download and read the file from a state agency. When reading the data with the popular <code>readr::read_delim()</code> function, the <code>col_date_mdy()</code> function can be used as a quick shortcut for <code>readr::col_date(format = &quot;%m/%d/%Y&quot;)</code>, the format most commonly found in U.S. campaign finance data.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> ex_file,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">trim_ws =</span> <span class="cn">FALSE</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">na =</span> <span class="fu">c</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;NA&quot;</span>, <span class="st">&quot;N/A&quot;</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col_types =</span> <span class="fu">cols</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">amount =</span> <span class="fu">col_number</span>(),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">col_date_mdy</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>We can see how the new <code>date</code> column is an actual date object, allowing for mathematical manipulation.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(vt<span class="sc">$</span>date)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] &quot;2009-03-09&quot;</span></span></code></pre></div>
<p>Next, we should try to normalize our data as much as possible. We can use some simple counting functions and built in vectors to check the cleanliness of our raw data.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_in</span>(vt<span class="sc">$</span>city, <span class="fu">str_to_lower</span>(valid_city))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.1</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_in</span>(vt<span class="sc">$</span>state, valid_state)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.4</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_in</span>(vt<span class="sc">$</span>zip, valid_zip)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.5</span></span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">col_stats</span>(vt, n_distinct)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 9 x 4</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   col     class      n     p</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 id      &lt;chr&gt;     10   1  </span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 cand    &lt;chr&gt;      3   0.3</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 date    &lt;date&gt;     9   0.9</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 amount  &lt;dbl&gt;      9   0.9</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 name    &lt;chr&gt;      9   0.9</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 address &lt;chr&gt;      9   0.9</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7 city    &lt;chr&gt;      9   0.9</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8 state   &lt;chr&gt;      7   0.7</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9 zip     &lt;chr&gt;      9   0.9</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">col_stats</span>(vt, count_na)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 9 x 4</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   col     class      n     p</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 id      &lt;chr&gt;      0   0  </span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 cand    &lt;chr&gt;      0   0  </span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 date    &lt;date&gt;     0   0  </span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 amount  &lt;dbl&gt;      0   0  </span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 name    &lt;chr&gt;      1   0.1</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 address &lt;chr&gt;      0   0  </span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7 city    &lt;chr&gt;      0   0  </span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8 state   &lt;chr&gt;      0   0  </span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9 zip     &lt;chr&gt;      0   0</span></span></code></pre></div>
<p>A typical benchmark is to reach greater than 95% <em>valid</em>. That is, we want to normalize our data enough that less than 5% of our data can not be easily confirmed as valid using a fairly comprehensive list of cities, states, and ZIP codes.</p>
<p>We will first try to reach this threshold by normalizing our data. This process involves reducing inconsistencies through string manipulation. There are separate <code>normal_*()</code> functions for each of the 4 types of geographic variables. Typically we use <code>dplyr::mutate()</code> to create <em>new</em>, normalized versions of our messy columns, preserving the old data for transparency. Here, we will just overwrite our example data for simplicity.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>vt <span class="ot">&lt;-</span> vt <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">address =</span> <span class="fu">normal_address</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">address =</span> address,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">abbs =</span> usps_street,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">na =</span> invalid_city,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">na_rep =</span> <span class="cn">TRUE</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">city =</span> <span class="fu">normal_city</span>(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">city =</span> city,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">abbs =</span> usps_city,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">states =</span> <span class="st">&quot;VT&quot;</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">na =</span> invalid_city</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">normal_state</span>(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">state =</span> state,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">abbreviate =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">na_rep =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">valid =</span> valid_state</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">zip =</span> <span class="fu">normal_zip</span>(</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">zip =</span> zip,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">na_rep =</span> <span class="cn">TRUE</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>We can see how these functions and our built in data was used to normalize the geographic contributor data and remove anything that didn’t present real information. This format is much more easily explored and search.</p>
<pre><code>#&gt; # A tibble: 10 x 4
#&gt;    address           city          state zip  
#&gt;    &lt;chr&gt;             &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;
#&gt;  1 4 SHEFFIELD SQ RD SHEFFIELD     VT    05866
#&gt;  2 &lt;NA&gt;              &lt;NA&gt;          &lt;NA&gt;  &lt;NA&gt; 
#&gt;  3 PO BOX 567        MIDLEBURY     VT    05753
#&gt;  4 SUGARHOUSE SQ     EAST CORINTH  VT    05076
#&gt;  5 4 SHEFFIELD SQ RD SHEFFIELD     VT    05866
#&gt;  6 55 THISPLACE AVE  YOUNG AMERICA MN    55555
#&gt;  7 11 LIBERTY AVE    BRISTOL       VT    &lt;NA&gt; 
#&gt;  8 2 BURLINGTON SQ   BRULINGTON    VT    05401
#&gt;  9 770 5TH ST NW     WASHINGTON    DC    20001
#&gt; 10 &lt;NA&gt;              SA            TX    78202</code></pre>
</div>
<div id="cities" class="section level2">
<h2>Cities</h2>
<p>However, the problem has not been solved. City names are the most troublesome; There are so many city names and such great variety (compared to states and ZIP codes), that it can be difficult to normalize and difficult to assess.</p>
<p>Our <code>valid_city</code> vector contains many city names, but far less than exist in the country, especially when you account for neighborhoods that aren’t <em>really</em> cities, but shouldn’t be changed (some of these are contained in our curated <code>extra_city</code> vector).</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(valid_city)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 19083</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(valid_city, <span class="dv">6</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] &quot;NEVADA&quot;       &quot;EASTLAND&quot;     &quot;PINECLIFFE&quot;   &quot;KASILOF&quot;      &quot;BARDSTOWN&quot;   </span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [6] &quot;ARENDTSVILLE&quot;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(extra_city, <span class="dv">6</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] &quot;NORTH CHARLEROI&quot; &quot;NATIONAL HARBOR&quot; &quot;BETHEL TOWNSHIP&quot; &quot;SUMMERSET&quot;      </span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [5] &quot;NASSAU BAY&quot;      &quot;RATHTON RD&quot;</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># combine both vectors</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>many_city <span class="ot">&lt;-</span> <span class="fu">c</span>(valid_city, extra_city)</span></code></pre></div>
<p>Still, checking against this list is a good way to check for values that need additional attention.</p>
<pre><code>#&gt; # A tibble: 3 x 5
#&gt;   id    city       state zip   valid
#&gt;   &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt; &lt;lgl&gt;
#&gt; 1 03    MIDLEBURY  VT    05753 FALSE
#&gt; 2 08    BRULINGTON VT    05401 FALSE
#&gt; 3 10    SA         TX    78202 FALSE</code></pre>
<p>It might not be clear what’s actually wrong with these values. A common way to check is by comparing them against <em>expected</em> city for a given ZIP code.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bad <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> bad,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> zipcodes,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;zip&quot;</span>, <span class="st">&quot;state&quot;</span>), </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">suffix =</span> <span class="fu">c</span>(<span class="st">&quot;_raw&quot;</span>, <span class="st">&quot;_match&quot;</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">city_raw</th>
<th align="left">state</th>
<th align="left">zip</th>
<th align="left">city_match</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">03</td>
<td align="left">MIDLEBURY</td>
<td align="left">VT</td>
<td align="left">05753</td>
<td align="left">MIDDLEBURY</td>
</tr>
<tr class="even">
<td align="left">08</td>
<td align="left">BRULINGTON</td>
<td align="left">VT</td>
<td align="left">05401</td>
<td align="left">BURLINGTON</td>
</tr>
<tr class="odd">
<td align="left">10</td>
<td align="left">SA</td>
<td align="left">TX</td>
<td align="left">78202</td>
<td align="left">SAN ANTONIO</td>
</tr>
</tbody>
</table>
<p>Now the problems become clear. Two city names are misspelled and the third is an obvious abbreviation. When dealing with millions of city names, we need a way to check each raw value against it’s expected ZIP code match.</p>
<p>The <code>str_dist()</code> and <code>is_abbrev()</code> functions can be used to compared the value we have with the value we expect. By only checking against the corresponding city to that record’s ZIP code, we are making extremely <em>confident</em> changes (compared to the incredibly useful clustering algorithms like those provided by the <code>refinr</code> package).</p>
<p>First, we can use <code>str_dist()</code> to check the <em>distance</em> between the two strings; distance is defined as the number of changes we’d need to make to our normalized value to get our expected matched value. If that distance is small (usually 1 or 2), we can pretty confidently use the matched value.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_dist</span>(<span class="st">&quot;example&quot;</span>, <span class="st">&quot;xampel&quot;</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 2</span></span></code></pre></div>
<p>But the string distance does not catch colloquial city abbreviations (e.g., NYC, BOS, LA, CHI, ABQ, BRNX, DFW, OKC). Many residents get so used to writing their city’s name they use abbreviations and assume them to be universally understood. The <code>is_abbrev()</code> function can be used to check to one string might be an abbreviation for another. Every abbreviation generated by the <code>abbreviate()</code> function satisfied the requirements of <code>is_abbrev()</code>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_abbrev</span>(<span class="at">abb =</span> <span class="st">&quot;NYC&quot;</span>, <span class="at">full =</span> <span class="st">&quot;New York City&quot;</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">is_abbrev</span>(<span class="at">abb =</span> <span class="st">&quot;DC&quot;</span>, <span class="at">full =</span> <span class="st">&quot;Washington&quot;</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span></code></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bad <span class="ot">&lt;-</span> bad <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">match_dist =</span> <span class="fu">str_dist</span>(city_raw, city_match),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">match_abb =</span> <span class="fu">is_abbrev</span>(city_raw, city_match)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">city_raw</th>
<th align="left">state</th>
<th align="left">zip</th>
<th align="left">city_match</th>
<th align="right">match_dist</th>
<th align="left">match_abb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">03</td>
<td align="left">MIDLEBURY</td>
<td align="left">VT</td>
<td align="left">05753</td>
<td align="left">MIDDLEBURY</td>
<td align="right">1</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">08</td>
<td align="left">BRULINGTON</td>
<td align="left">VT</td>
<td align="left">05401</td>
<td align="left">BURLINGTON</td>
<td align="right">1</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">10</td>
<td align="left">SA</td>
<td align="left">TX</td>
<td align="left">78202</td>
<td align="left">SAN ANTONIO</td>
<td align="right">9</td>
<td align="left">TRUE</td>
</tr>
</tbody>
</table>
<p>Here’s what this process would look like when employed on an entire data frame. It’s important to ensure that the number of rows in our campaign finance data is kept consistent throughout the wrangling process and that original columns are left unchanged.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>vt <span class="ot">&lt;-</span> vt <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">city_raw =</span> city) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># match city by ZIP</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(zipcodes) <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">city_match =</span> city) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># check against match</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">match_dist =</span> <span class="fu">str_dist</span>(city_raw, city_match),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">match_abb =</span> <span class="fu">is_abbrev</span>(city_raw, city_match),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">city =</span> <span class="fu">ifelse</span>(match_abb <span class="sc">|</span> match_dist <span class="sc">==</span> <span class="dv">1</span>, city_match, city_raw)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove intermediary columns</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>city_raw, <span class="sc">-</span>city_match, <span class="sc">-</span>match_dist, <span class="sc">-</span>match_abb)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Joining, by = c(&quot;state&quot;, &quot;zip&quot;)</span></span></code></pre></div>
<p>Now every <code>city</code>, <code>state</code>, and <code>zip</code> value is contained in our list of valid values.</p>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">state</th>
<th align="left">zip</th>
<th align="left">city</th>
<th align="left">all_valid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">01</td>
<td align="left">VT</td>
<td align="left">05866</td>
<td align="left">SHEFFIELD</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">03</td>
<td align="left">VT</td>
<td align="left">05753</td>
<td align="left">MIDDLEBURY</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">04</td>
<td align="left">VT</td>
<td align="left">05076</td>
<td align="left">EAST CORINTH</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">05</td>
<td align="left">VT</td>
<td align="left">05866</td>
<td align="left">SHEFFIELD</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">06</td>
<td align="left">MN</td>
<td align="left">55555</td>
<td align="left">YOUNG AMERICA</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">08</td>
<td align="left">VT</td>
<td align="left">05401</td>
<td align="left">BURLINGTON</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">09</td>
<td align="left">DC</td>
<td align="left">20001</td>
<td align="left">WASHINGTON</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">TX</td>
<td align="left">78202</td>
<td align="left">SAN ANTONIO</td>
<td align="left">TRUE</td>
</tr>
</tbody>
</table>
<p>Once our data is as normal as we can confidently make it, we can begin to explore. First, we’ll explore the data for missing values with <code>flag_na()</code>, which takes a <a href="https://github.com/r-lib/tidyselect" title="tidyselect">tidyselect</a> input of columns (or something like <code>dplyr::everything()</code>).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(vt <span class="ot">&lt;-</span> <span class="fu">flag_na</span>(vt, name))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 10 x 10</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    id    cand    date       amount name    address   state zip   city    na_flag</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;lgl&gt;  </span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 01    Bob Mi… 2019-02-09     10 Lisa M… 4 SHEFFI… VT    05866 SHEFFI… FALSE  </span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 02    Bob Mi… 2009-03-09     20 Deb Br… &lt;NA&gt;      &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;    FALSE  </span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 03    Chuck … 2019-04-09     25 &lt;NA&gt;    PO BOX 5… VT    05753 MIDDLE… TRUE   </span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 04    Chuck … 2019-05-09    100 Josh J… SUGARHOU… VT    05076 EAST C… FALSE  </span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 05    Bob Mi… 2019-02-09     10 Lisa M… 4 SHEFFI… VT    05866 SHEFFI… FALSE  </span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 06    Chuck … 2019-06-09   1000 Bob Ta… 55 THISP… MN    55555 YOUNG … FALSE  </span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 07    Chuck … 2019-07-09   -600 Alex J… 11 LIBER… VT    &lt;NA&gt;  &lt;NA&gt;    FALSE  </span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 08    Alice … 2019-08-09      0 Ruth S… 2 BURLIN… VT    05401 BURLIN… FALSE  </span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 09    Alice … 2019-09-09     69 Joe Ga… 770 5TH … DC    20001 WASHIN… FALSE  </span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 10    Alice … 2019-11-09    222 Dave W… &lt;NA&gt;      TX    78202 SAN AN… FALSE</span></span></code></pre></div>
<p>Next, we’ll want to check for duplicate rows using <code>flag_dupes()</code>, which takes the same kind of arguments. Here, we can ignore the supposedly unique <code>id</code> variable. It’s possible for a person to make the same contribution on the same date, but we should flag them nonetheless.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(vt <span class="ot">&lt;-</span> <span class="fu">flag_dupes</span>(vt, <span class="sc">-</span>id, <span class="at">.both =</span> <span class="cn">TRUE</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 10 x 11</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    id    cand    date       amount name    address   state zip   city    na_flag</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;lgl&gt;  </span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 01    Bob Mi… 2019-02-09     10 Lisa M… 4 SHEFFI… VT    05866 SHEFFI… FALSE  </span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 02    Bob Mi… 2009-03-09     20 Deb Br… &lt;NA&gt;      &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;    FALSE  </span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 03    Chuck … 2019-04-09     25 &lt;NA&gt;    PO BOX 5… VT    05753 MIDDLE… TRUE   </span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 04    Chuck … 2019-05-09    100 Josh J… SUGARHOU… VT    05076 EAST C… FALSE  </span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 05    Bob Mi… 2019-02-09     10 Lisa M… 4 SHEFFI… VT    05866 SHEFFI… FALSE  </span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 06    Chuck … 2019-06-09   1000 Bob Ta… 55 THISP… MN    55555 YOUNG … FALSE  </span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 07    Chuck … 2019-07-09   -600 Alex J… 11 LIBER… VT    &lt;NA&gt;  &lt;NA&gt;    FALSE  </span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 08    Alice … 2019-08-09      0 Ruth S… 2 BURLIN… VT    05401 BURLIN… FALSE  </span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 09    Alice … 2019-09-09     69 Joe Ga… 770 5TH … DC    20001 WASHIN… FALSE  </span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 10    Alice … 2019-11-09    222 Dave W… &lt;NA&gt;      TX    78202 SAN AN… FALSE  </span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with 1 more variable: dupe_flag &lt;lgl&gt;</span></span></code></pre></div>
</div>
<div id="conclude" class="section level2">
<h2>Conclude</h2>
<p>This normalized data is now ready to be uploaded to the Accountability Project and searched alongside <a href="https://investigativereportingworkshop.org/2021/02/17/1-billion-records-and-counting-the-accountability-project-reaches-new-milestone/"><em>1 billion</em> other records</a>! These cleaned names and addresses might bring up search results alongside one of our other sets of public data: campaign expenditures, registered voters, nonprofit organizations, stimulus spending, government contracts, lobbyist registrations, etc.</p>
<table>
<colgroup>
<col width="2%" />
<col width="11%" />
<col width="10%" />
<col width="6%" />
<col width="12%" />
<col width="16%" />
<col width="5%" />
<col width="5%" />
<col width="12%" />
<col width="7%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">cand</th>
<th align="left">date</th>
<th align="right">amount</th>
<th align="left">name</th>
<th align="left">address</th>
<th align="left">state</th>
<th align="left">zip</th>
<th align="left">city</th>
<th align="left">na_flag</th>
<th align="left">dupe_flag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">01</td>
<td align="left">Bob Miller</td>
<td align="left">2019-02-09</td>
<td align="right">10</td>
<td align="left">Lisa Miller</td>
<td align="left">4 SHEFFIELD SQ RD</td>
<td align="left">VT</td>
<td align="left">05866</td>
<td align="left">SHEFFIELD</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">02</td>
<td align="left">Bob Miller</td>
<td align="left">2009-03-09</td>
<td align="right">20</td>
<td align="left">Deb Brown</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">03</td>
<td align="left">Chuck White</td>
<td align="left">2019-04-09</td>
<td align="right">25</td>
<td align="left">NA</td>
<td align="left">PO BOX 567</td>
<td align="left">VT</td>
<td align="left">05753</td>
<td align="left">MIDDLEBURY</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">04</td>
<td align="left">Chuck White</td>
<td align="left">2019-05-09</td>
<td align="right">100</td>
<td align="left">Josh Jones</td>
<td align="left">SUGARHOUSE SQ</td>
<td align="left">VT</td>
<td align="left">05076</td>
<td align="left">EAST CORINTH</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">05</td>
<td align="left">Bob Miller</td>
<td align="left">2019-02-09</td>
<td align="right">10</td>
<td align="left">Lisa Miller</td>
<td align="left">4 SHEFFIELD SQ RD</td>
<td align="left">VT</td>
<td align="left">05866</td>
<td align="left">SHEFFIELD</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">06</td>
<td align="left">Chuck White</td>
<td align="left">2019-06-09</td>
<td align="right">1000</td>
<td align="left">Bob Taylor</td>
<td align="left">55 THISPLACE AVE</td>
<td align="left">MN</td>
<td align="left">55555</td>
<td align="left">YOUNG AMERICA</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">07</td>
<td align="left">Chuck White</td>
<td align="left">2019-07-09</td>
<td align="right">-600</td>
<td align="left">Alex Johnson</td>
<td align="left">11 LIBERTY AVE</td>
<td align="left">VT</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">08</td>
<td align="left">Alice Walsh</td>
<td align="left">2019-08-09</td>
<td align="right">0</td>
<td align="left">Ruth Smith</td>
<td align="left">2 BURLINGTON SQ</td>
<td align="left">VT</td>
<td align="left">05401</td>
<td align="left">BURLINGTON</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">09</td>
<td align="left">Alice Walsh</td>
<td align="left">2019-09-09</td>
<td align="right">69</td>
<td align="left">Joe Garcia</td>
<td align="left">770 5TH ST NW</td>
<td align="left">DC</td>
<td align="left">20001</td>
<td align="left">WASHINGTON</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">Alice Walsh</td>
<td align="left">2019-11-09</td>
<td align="right">222</td>
<td align="left">Dave Wilson</td>
<td align="left">NA</td>
<td align="left">TX</td>
<td align="left">78202</td>
<td align="left">SAN ANTONIO</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
</tr>
</tbody>
</table>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
